stages:
  - build
  - deploy

build_job:
  stage: build
  image: node:20
  script:
    - node -v
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

deploy_job:
  stage: deploy
  script:
    - echo "Deploy Success"